# Generated by Django 5.1.1 on 2025-02-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_paid',
            field=models.BooleanField(default=False),
        ),
    ]
